---
name: bug-bounty
full_name: Bug Bounty
description: A microsite for our bug bounty 
impact: Allow security researchers to report security issues to 18F.
owner_type: working-group
stage: discovery
testable: true

licenses:
  dj-database-url:
    name: BSD-3-Clause
    url: http://opensource.org/licenses/BSD-3-Clause
  Django:
    name: BSD-3-Clause
    url: http://opensource.org/licenses/BSD-3-Clause
  django-enumfields:
    name: MIT
    url: https://opensource.org/licenses/MIT
  django-floppyforms:
    name: BSD licence, see LICENSE file
    url: FIXME
  python-markdown:
    name: BSD-3-Clause
    url: http://opensource.org/licenses/BSD-3-Clause
  psycopg2:
    name: LGPL-3.0
    url: http://www.gnu.org/licenses/lgpl-3.0-standalone.html
  six:
    name: MIT
    url: https://opensource.org/licenses/MIT
  virtualenv:
    name: MIT
    url: https://opensource.org/licenses/MIT
  WebOb:
    name: MIT
    url: https://opensource.org/licenses/MIT
  whitenoise:
    name: MIT
    url: https://opensource.org/licenses/MIT
  wsgi-basic-auth:
    name: MIT
    url: https://opensource.org/licenses/MIT
  requests:
    name: Apache-2.0
    url: https://opensource.org/licenses/Apache-2.0

partners:
- 18f

team:
- github: jacobian
  id: Jacob Kaplan-Moss
  role: Lead
- github: konklone
  id: Eric Mill
  role: Instigator

type: app

links:
- url: https://no.site.yet.example.com/
  text: Bug Bounty Site

blogTag: 
  - security
  - bug bounty
  - cyber

tags: 
  - security
  - bug bounty
  - cyber

stack:
- Django
- PostgreSQL