# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbounty', '0003_add_bounty_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='slack_channel',
            field=models.TextField(blank=True, help_text='notifications about new reports will be posted to this channel.'),
        ),
    ]
